Repository ucsb-cs156-s23/proj-courses-s23-7pm-2, pull requests merged in 2023-06, with the labels that each got.

#24 mm-addedGradeRepository
  src/main/java/edu/ucsb/cs156/courses/entities/Grade.java
  src/main/java/edu/ucsb/cs156/courses/repositories/GradeRepository.java
Labels: Needs Staff Approval

#25 Fix trivial stryker comments
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/BasicCourseSearch/CourseOverTimeSearchForm.js
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/components/Courses/CourseTable.js
  frontend/src/main/components/Jobs/UpdateCoursesJobForm.js
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/components/Utils/Plaintext.js
  frontend/src/main/utils/useBackend.js
Labels: Needs Staff Approval

#11 added the professor menu option
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/CourseByInstructor/CourseByInstructorIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/CourseByInstructor/CourseByInstructorIndexPage.test.js
Labels: 10, Merge Candidate-CI/CD

#39 CompactedNavBar
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: Needs Staff Approval

#36 Revamp Course By Instructor Backend
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseByInstructorController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseByInstructorControllerTests.java
Labels: 10

#31 Add checkbox instructor form
  frontend/src/main/components/BasicCourseSearch/CourseByInstructorSearchForm.js
  frontend/src/main/pages/CourseByInstructor/CourseByInstructorIndexPage.js
  frontend/src/tests/components/BasicCourseSearch/CourseByInstructorSearchForm.test.js
  frontend/src/tests/pages/CourseByInstructor/CourseByInstructorIndexPage.test.js
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseByInstructorController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseByInstructorControllerTests.java
Labels: Needs Staff Approval
